# Generated by Django 4.0.6 on 2022-08-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cv', models.TextField()),
                ('linkedin', models.URLField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.TextField(choices=[('n', 'none'), ('m', 'male'), ('f', 'female')], default='n', max_length=1)),
                ('status', models.TextField(choices=[('p', 'pending'), ('i', 'inProgress'), ('a', 'accepted'), ('f', 'failed')], default='p', max_length=1)),
            ],
        ),
    ]
