# Generated by Django 4.0.6 on 2022-08-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_tracking_system', '0005_alter_applicant_gender_alter_applicant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='type',
            field=models.CharField(choices=[('phone', 'phone'), ('technical', 'technical'), ('code', 'code'), ('final', 'final')], default='p', max_length=9),
        ),
    ]
